<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>TypeError: "bool" object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a bool. // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css"
        type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does
         not by accident trigger a request to /favicon.ico which might
         change the application state. -->
    <link rel="shortcut icon"
        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 2572697513656,
          CONSOLE_MODE = false,
          EVALEX = true,
          EVALEX_TRUSTED = false,
          SECRET = "4agyREnnkLcTKMoQHIPV";
    </script>
  </head>
  <body style="background-color: #fff">
    <div class="debugger">
<h1>builtins.TypeError</h1>
<div class="detail">
  <p class="errormsg">TypeError: "bool" object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a bool.</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-2572697703088">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask\app.py"</cite>,
      line <em class="line">2309</em>,
      in <code class="function">__call__</code></h4>
  <div class="source"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def __call__(self, environ, start_response):</pre>
<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;The WSGI server calls the Flask application object as the</pre>
<pre class="line before"><span class="ws">        </span>WSGI application. This calls :meth:`wsgi_app` which can be</pre>
<pre class="line before"><span class="ws">        </span>wrapped to applying middleware.&quot;&quot;&quot;</pre>
<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def __repr__(self):</pre>
<pre class="line after"><span class="ws">        </span>return "&lt;%s %r&gt;" % (</pre>
<pre class="line after"><span class="ws">            </span>self.__class__.__name__,</pre>
<pre class="line after"><span class="ws">            </span>self.name,</pre></div>
</div>

<li><div class="frame" id="frame-2572697661512">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask\app.py"</cite>,
      line <em class="line">2295</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source"><pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>ctx.push()</pre>
<pre class="line before"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line before"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line before"><span class="ws">                </span>error = e</pre>
<pre class="line current"><span class="ws">                </span>response = self.handle_exception(e)</pre>
<pre class="line after"><span class="ws">            </span>except:</pre>
<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre>
<pre class="line after"><span class="ws">                </span>raise</pre>
<pre class="line after"><span class="ws">            </span>return response(environ, start_response)</pre>
<pre class="line after"><span class="ws">        </span>finally:</pre></div>
</div>

<li><div class="frame" id="frame-2572697661848">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask_cors\extension.py"</cite>,
      line <em class="line">161</em>,
      in <code class="function">wrapped_function</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span># Wrap exception handlers with cross_origin</pre>
<pre class="line before"><span class="ws">        </span># These error handlers will still respect the behavior of the route</pre>
<pre class="line before"><span class="ws">        </span>if options.get("intercept_exceptions", true):</pre>
<pre class="line before"><span class="ws">            </span>def _after_request_decorator(f):</pre>
<pre class="line before"><span class="ws">                </span>def wrapped_function(*args, **kwargs):</pre>
<pre class="line current"><span class="ws">                    </span>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre>
<pre class="line after"><span class="ws">                </span>return wrapped_function</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">            </span>if hasattr(app, "handle_exception"):</pre>
<pre class="line after"><span class="ws">                </span>app.handle_exception = _after_request_decorator(</pre>
<pre class="line after"><span class="ws">                    </span>app.handle_exception)</pre></div>
</div>

<li><div class="frame" id="frame-2572697661568">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1741</em>,
      in <code class="function">handle_exception</code></h4>
  <div class="source"><pre class="line before"><span class="ws">            </span># if we want to repropagate the exception, we can attempt to</pre>
<pre class="line before"><span class="ws">            </span># raise it with the whole traceback in case we can do that</pre>
<pre class="line before"><span class="ws">            </span># (the function was actually called from the except part)</pre>
<pre class="line before"><span class="ws">            </span># otherwise, we just raise the error again</pre>
<pre class="line before"><span class="ws">            </span>if exc_value is e:</pre>
<pre class="line current"><span class="ws">                </span>reraise(exc_type, exc_value, tb)</pre>
<pre class="line after"><span class="ws">            </span>else:</pre>
<pre class="line after"><span class="ws">                </span>raise e</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>self.log_exception((exc_type, exc_value, tb))</pre>
<pre class="line after"><span class="ws">        </span>if handler is None:</pre></div>
</div>

<li><div class="frame" id="frame-2572697745504">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask\_compat.py"</cite>,
      line <em class="line">35</em>,
      in <code class="function">reraise</code></h4>
  <div class="source"><pre class="line before"><span class="ws">    </span>from io import StringIO</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def reraise(tp, value, tb=None):</pre>
<pre class="line before"><span class="ws">        </span>if value.__traceback__ is not tb:</pre>
<pre class="line before"><span class="ws">            </span>raise value.with_traceback(tb)</pre>
<pre class="line current"><span class="ws">        </span>raise value</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>implements_to_string = _identity</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>else:</pre>
<pre class="line after"><span class="ws">    </span>text_type = unicode</pre></div>
</div>

<li><div class="frame" id="frame-2572697791792">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask\app.py"</cite>,
      line <em class="line">2292</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>ctx = self.request_context(environ)</pre>
<pre class="line before"><span class="ws">        </span>error = None</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>ctx.push()</pre>
<pre class="line current"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line after"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">                </span>error = e</pre>
<pre class="line after"><span class="ws">                </span>response = self.handle_exception(e)</pre>
<pre class="line after"><span class="ws">            </span>except:</pre>
<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre></div>
</div>

<li><div class="frame" id="frame-2572697790840">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1816</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source"><pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line before"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line before"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line before"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line current"><span class="ws">        </span>return self.finalize_request(rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def finalize_request(self, rv, from_error_handler=false):</pre>
<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Given the return value from a view function this finalizes</pre>
<pre class="line after"><span class="ws">        </span>the request by converting it into a response and invoking the</pre>
<pre class="line after"><span class="ws">        </span>postprocessing functions.  This is invoked for both normal</pre></div>
</div>

<li><div class="frame" id="frame-2572697792296">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1831</em>,
      in <code class="function">finalize_request</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>with the `from_error_handler` flag.  If enabled, failures in</pre>
<pre class="line before"><span class="ws">        </span>response processing will be logged and otherwise ignored.</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">        </span>:internal:</pre>
<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;</pre>
<pre class="line current"><span class="ws">        </span>response = self.make_response(rv)</pre>
<pre class="line after"><span class="ws">        </span>try:</pre>
<pre class="line after"><span class="ws">            </span>response = self.process_response(response)</pre>
<pre class="line after"><span class="ws">            </span>request_finished.send(self, response=response)</pre>
<pre class="line after"><span class="ws">        </span>except Exception:</pre>
<pre class="line after"><span class="ws">            </span>if not from_error_handler:</pre></div>
</div>

<li><div class="frame" id="frame-2572697792408">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1982</em>,
      in <code class="function">make_response</code></h4>
  <div class="source"><pre class="line before"><span class="ws">                        </span>"{e}\nThe view function did not return a valid"</pre>
<pre class="line before"><span class="ws">                        </span>" response. The return type must be a string, tuple,"</pre>
<pre class="line before"><span class="ws">                        </span>" Response instance, or WSGI callable, but it was a"</pre>
<pre class="line before"><span class="ws">                        </span>" {rv.__class__.__name__}.".format(e=e, rv=rv)</pre>
<pre class="line before"><span class="ws">                    </span>)</pre>
<pre class="line current"><span class="ws">                    </span>reraise(TypeError, new_error, sys.exc_info()[2])</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span># prefer the status if it was provided</pre>
<pre class="line after"><span class="ws">        </span>if status is not None:</pre>
<pre class="line after"><span class="ws">            </span>if isinstance(status, (text_type, bytes, bytearray)):</pre>
<pre class="line after"><span class="ws">                </span>rv.status = status</pre></div>
</div>

<li><div class="frame" id="frame-2572697791848">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask\_compat.py"</cite>,
      line <em class="line">34</em>,
      in <code class="function">reraise</code></h4>
  <div class="source"><pre class="line before"><span class="ws">    </span>from inspect import getfullargspec as getargspec</pre>
<pre class="line before"><span class="ws">    </span>from io import StringIO</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def reraise(tp, value, tb=None):</pre>
<pre class="line before"><span class="ws">        </span>if value.__traceback__ is not tb:</pre>
<pre class="line current"><span class="ws">            </span>raise value.with_traceback(tb)</pre>
<pre class="line after"><span class="ws">        </span>raise value</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>implements_to_string = _identity</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>else:</pre></div>
</div>

<li><div class="frame" id="frame-2572697792016">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\flask\app.py"</cite>,
      line <em class="line">1974</em>,
      in <code class="function">make_response</code></h4>
  <div class="source"><pre class="line before"><span class="ws">                </span>status = headers = None</pre>
<pre class="line before"><span class="ws">            </span>else:</pre>
<pre class="line before"><span class="ws">                </span># evaluate a WSGI callable, or coerce a different response</pre>
<pre class="line before"><span class="ws">                </span># class to the correct type</pre>
<pre class="line before"><span class="ws">                </span>try:</pre>
<pre class="line current"><span class="ws">                    </span>rv = self.response_class.force_type(rv, request.environ)</pre>
<pre class="line after"><span class="ws">                </span>except TypeError as e:</pre>
<pre class="line after"><span class="ws">                    </span>new_error = TypeError(</pre>
<pre class="line after"><span class="ws">                        </span>"{e}\nThe view function did not return a valid"</pre>
<pre class="line after"><span class="ws">                        </span>" response. The return type must be a string, tuple,"</pre>
<pre class="line after"><span class="ws">                        </span>" Response instance, or WSGI callable, but it was a"</pre></div>
</div>

<li><div class="frame" id="frame-2572697854696">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\werkzeug\wrappers.py"</cite>,
      line <em class="line">921</em>,
      in <code class="function">force_type</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;</pre>
<pre class="line before"><span class="ws">        </span>if not isinstance(response, BaseResponse):</pre>
<pre class="line before"><span class="ws">            </span>if environ is None:</pre>
<pre class="line before"><span class="ws">                </span>raise TypeError("cannot convert WSGI application into "</pre>
<pre class="line before"><span class="ws">                                </span>"response objects without an environ")</pre>
<pre class="line current"><span class="ws">            </span>response = BaseResponse(*_run_wsgi_app(response, environ))</pre>
<pre class="line after"><span class="ws">        </span>response.__class__ = cls</pre>
<pre class="line after"><span class="ws">        </span>return response</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>@classmethod</pre>
<pre class="line after"><span class="ws">    </span>def from_app(cls, app, environ, buffered=false):</pre></div>
</div>

<li><div class="frame" id="frame-2572697854024">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\werkzeug\wrappers.py"</cite>,
      line <em class="line">59</em>,
      in <code class="function">_run_wsgi_app</code></h4>
  <div class="source"><pre class="line before"><span class="ws">    </span>&quot;&quot;&quot;This function replaces itself to ensure that the test module is not</pre>
<pre class="line before"><span class="ws">    </span>imported unless required.  DO NOT USE!</pre>
<pre class="line before"><span class="ws">    </span>&quot;&quot;&quot;</pre>
<pre class="line before"><span class="ws">    </span>global _run_wsgi_app</pre>
<pre class="line before"><span class="ws">    </span>from werkzeug.test import run_wsgi_app as _run_wsgi_app</pre>
<pre class="line current"><span class="ws">    </span>return _run_wsgi_app(*args)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span>def _warn_if_string(iterable):</pre>
<pre class="line after"><span class="ws">    </span>&quot;&quot;&quot;Helper for the response objects to check if the iterable returned</pre>
<pre class="line after"><span class="ws">    </span>to the WSGI server is not a string.</pre></div>
</div>

<li><div class="frame" id="frame-2572697854472">
  <h4>File <cite class="filename">"C:\Program Files\Python36\lib\site-packages\werkzeug\test.py"</cite>,
      line <em class="line">923</em>,
      in <code class="function">run_wsgi_app</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>if exc_info is not None:</pre>
<pre class="line before"><span class="ws">            </span>reraise(*exc_info)</pre>
<pre class="line before"><span class="ws">        </span>response[:] = [status, headers]</pre>
<pre class="line before"><span class="ws">        </span>return buffer.append</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line current"><span class="ws">    </span>app_rv = app(environ, start_response)</pre>
<pre class="line after"><span class="ws">    </span>close_func = getattr(app_rv, "close", None)</pre>
<pre class="line after"><span class="ws">    </span>app_iter = iter(app_rv)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span># when buffering we emit the close call early and convert the</pre>
<pre class="line after"><span class="ws">    </span># application iterator into a regular list</pre></div>
</div>
</ul>
  <blockquote>TypeError: "bool" object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a bool.</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File &quot;C:\Program Files\Python36\lib\site-packages\flask\app.py&quot;, line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File &quot;C:\Program Files\Python36\lib\site-packages\flask\app.py&quot;, line 2295, in wsgi_app
    response = self.handle_exception(e)
  File &quot;C:\Program Files\Python36\lib\site-packages\flask_cors\extension.py&quot;, line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File &quot;C:\Program Files\Python36\lib\site-packages\flask\app.py&quot;, line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File &quot;C:\Program Files\Python36\lib\site-packages\flask\_compat.py&quot;, line 35, in reraise
    raise value
  File &quot;C:\Program Files\Python36\lib\site-packages\flask\app.py&quot;, line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File &quot;C:\Program Files\Python36\lib\site-packages\flask\app.py&quot;, line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File &quot;C:\Program Files\Python36\lib\site-packages\flask\app.py&quot;, line 1831, in finalize_request
    response = self.make_response(rv)
  File &quot;C:\Program Files\Python36\lib\site-packages\flask\app.py&quot;, line 1982, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File &quot;C:\Program Files\Python36\lib\site-packages\flask\_compat.py&quot;, line 34, in reraise
    raise value.with_traceback(tb)
  File &quot;C:\Program Files\Python36\lib\site-packages\flask\app.py&quot;, line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File &quot;C:\Program Files\Python36\lib\site-packages\werkzeug\wrappers.py&quot;, line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File &quot;C:\Program Files\Python36\lib\site-packages\werkzeug\wrappers.py&quot;, line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File &quot;C:\Program Files\Python36\lib\site-packages\werkzeug\test.py&quot;, line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: "bool" object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a bool.</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON"T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>

    <div class="pin-prompt">
      <div class="inner">
        <h3>Console Locked</h3>
        <p>
          The console is locked and needs to be unlocked by entering the PIN.
          You can find the PIN printed out on the standard output of your
          shell that runs the server.
        <form>
          <p>PIN:
            <input type=text name=pin size=14>
            <input type=submit name=btn value="Confirm Pin">
        </form>
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files\Python36\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Program Files\Python36\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Program Files\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python36\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Program Files\Python36\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "C:\Program Files\Python36\lib\site-packages\flask\app.py", line 1982, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "C:\Program Files\Python36\lib\site-packages\flask\_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files\Python36\lib\site-packages\flask\app.py", line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "C:\Program Files\Python36\lib\site-packages\werkzeug\wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "C:\Program Files\Python36\lib\site-packages\werkzeug\wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "C:\Program Files\Python36\lib\site-packages\werkzeug\test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: "bool" object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a bool.

-->
